name: form_builder_extra_fields
description: Additional ready-made form input fields for flutter_form_builder package
version: 9.0.2
environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.2.0
  flutter_colorpicker: ^1.0.3
  dropdown_search: ^6.0.2
  signature: ^6.3.0
  intl: ^0.20.2
  flutter_typeahead:
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
